In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2023-08-12,12:30,Premier League,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,...,Match Report,NaN,15.0,7.0,19.1,0.0,0,0,2024,Arsenal
2,2023-08-21,20:00,Premier League,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,...,Match Report,NaN,13.0,2.0,16.4,0.0,1,1,2024,Arsenal
3,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,...,Match Report,NaN,18.0,9.0,13.8,0.0,1,1,2024,Arsenal
4,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,...,Match Report,NaN,17.0,5.0,15.0,0.0,0,0,2024,Arsenal
5,2023-09-17,16:30,Premier League,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,...,Match Report,NaN,13.0,4.0,17.4,0.0,0,0,2024,Arsenal

In [4]:
matches.shape

(2986, 27)

### missing values

In [7]:
# 4 seasons * 20 squads * 38 matches

4 * 20 * 38

3040

In [13]:
# missing rows -> bottom 3 team gets demoted, league is still on going
matches["team"].value_counts()

team
Arsenal                     150
Everton                     150
Wolverhampton Wanderers     150
Newcastle United            149
Manchester City             149
West Ham United             149
Crystal Palace              149
Aston Villa                 149
Liverpool                   149
Chelsea                     148
Tottenham Hotspur           148
Brighton and Hove Albion    148
Manchester United           148
Leicester City              114
Southampton                 114
Leeds United                114
Fulham                      112
Brentford                   112
Burnley                     112
Nottingham Forest            74
Sheffield United             74
Bournemouth                  74
Watford                      38
Norwich City                 38
West Bromwich Albion         38
Luton Town                   36
Name: count, dtype: int64

In [14]:
matches[matches["team"] == "Arsenal"].sort_values("date")

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2020-09-12,12:30,Premier League,Matchweek 1,Sat,Away,W,3.0,0.0,Fulham,...,Match Report,NaN,13.0,5.0,14.1,2.0,0,0,2021,Arsenal
2,2020-09-19,20:00,Premier League,Matchweek 2,Sat,Home,W,2.0,1.0,West Ham,...,Match Report,NaN,7.0,3.0,14.8,0.0,0,0,2021,Arsenal
4,2020-09-28,20:00,Premier League,Matchweek 3,Mon,Away,L,1.0,3.0,Liverpool,...,Match Report,NaN,4.0,3.0,15.0,0.0,0,0,2021,Arsenal
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,Match Report,NaN,6.0,5.0,16.3,0.0,0,0,2021,Arsenal
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,Match Report,NaN,11.0,3.0,18.4,2.0,0,0,2021,Arsenal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,2024-04-14,16:30,Premier League,Matchweek 33,Sun,Home,L,0.0,2.0,Aston Villa,...,Match Report,NaN,18.0,4.0,17.2,1.0,0,0,2024,Arsenal
46,2024-04-20,19:30,Premier League,Matchweek 34,Sat,Away,W,2.0,0.0,Wolves,...,Match Report,NaN,24.0,9.0,17.8,0.0,0,0,2024,Arsenal
47,2024-04-23,20:00,Premier League,Matchweek 29,Tue,Home,W,5.0,0.0,Chelsea,...,Match Report,NaN,27.0,10.0,16.3,0.0,0,0,2024,Arsenal
48,2024-04-28,14:00,Premier League,Matchweek 35,Sun,Away,W,3.0,2.0,Tottenham,...,Match Report,NaN,9.0,3.0,14.3,1.0,0,0,2024,Arsenal
49,2024-05-04,12:30,Premier League,Matchweek 36,Sat,Home,W,3.0,0.0,Bournemouth,...,Match Report,NaN,23.0,8.0,13.7,0.0,1,1,2024,Arsenal

In [15]:
matches["round"].value_counts()

round
Matchweek 1     80
Matchweek 27    80
Matchweek 21    80
Matchweek 22    80
Matchweek 23    80
Matchweek 24    80
Matchweek 25    80
Matchweek 26    80
Matchweek 28    80
Matchweek 19    80
Matchweek 30    80
Matchweek 31    80
Matchweek 32    80
Matchweek 33    80
Matchweek 29    80
Matchweek 35    80
Matchweek 2     80
Matchweek 20    80
Matchweek 18    80
Matchweek 9     80
Matchweek 3     80
Matchweek 4     80
Matchweek 5     80
Matchweek 6     80
Matchweek 7     80
Matchweek 17    80
Matchweek 8     80
Matchweek 10    80
Matchweek 11    80
Matchweek 12    80
Matchweek 13    80
Matchweek 14    80
Matchweek 15    80
Matchweek 16    80
Matchweek 34    74
Matchweek 36    72
Matchweek 37    60
Matchweek 38    60
Name: count, dtype: int64

In [19]:
# object to datetime
matches["date"] = pd.to_datetime(matches["date"])

In [21]:
matches.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                       int64
pkatt                    int64
season                   int64
team                    object
dtype: object

In [22]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [23]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,notes,sh,sot,dist,fk,pk,pkatt,season,team,venue_code
1,2023-08-12,12:30,Premier League,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,...,NaN,15.0,7.0,19.1,0.0,0,0,2024,Arsenal,1
2,2023-08-21,20:00,Premier League,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,...,NaN,13.0,2.0,16.4,0.0,1,1,2024,Arsenal,0
3,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,...,NaN,18.0,9.0,13.8,0.0,1,1,2024,Arsenal,1
4,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,...,NaN,17.0,5.0,15.0,0.0,0,0,2024,Arsenal,1
5,2023-09-17,16:30,Premier League,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,...,NaN,13.0,4.0,17.4,0.0,0,0,2024,Arsenal,0

In [24]:
# 0 away
# 1 home

In [25]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [26]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,sh,sot,dist,fk,pk,pkatt,season,team,venue_code,opp_code
1,2023-08-12,12:30,Premier League,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,...,15.0,7.0,19.1,0.0,0,0,2024,Arsenal,1,18
2,2023-08-21,20:00,Premier League,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,...,13.0,2.0,16.4,0.0,1,1,2024,Arsenal,0,7
3,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,...,18.0,9.0,13.8,0.0,1,1,2024,Arsenal,1,9
4,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,...,17.0,5.0,15.0,0.0,0,0,2024,Arsenal,1,15
5,2023-09-17,16:30,Premier League,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,...,13.0,4.0,17.4,0.0,0,0,2024,Arsenal,0,8

In [27]:
# hh:mm -> hh
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [28]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,sot,dist,fk,pk,pkatt,season,team,venue_code,opp_code,hour
1,2023-08-12,12:30,Premier League,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,...,7.0,19.1,0.0,0,0,2024,Arsenal,1,18,12
2,2023-08-21,20:00,Premier League,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,...,2.0,16.4,0.0,1,1,2024,Arsenal,0,7,20
3,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,...,9.0,13.8,0.0,1,1,2024,Arsenal,1,9,15
4,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,...,5.0,15.0,0.0,0,0,2024,Arsenal,1,15,16
5,2023-09-17,16:30,Premier League,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,...,4.0,17.4,0.0,0,0,2024,Arsenal,0,8,16

In [29]:
matches["day_code"] = matches["date"].dt.dayofweek

### initial model

In [30]:
matches["target"] = (matches["result"] == "W").astype("int")
# 0 - draw , loss
# 1 - win

In [31]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2023-08-12,12:30,Premier League,Matchweek 1,Sat,Home,W,2.0,1.0,Nott'ham Forest,...,0.0,0,0,2024,Arsenal,1,18,12,5,1
2,2023-08-21,20:00,Premier League,Matchweek 2,Mon,Away,W,1.0,0.0,Crystal Palace,...,0.0,1,1,2024,Arsenal,0,7,20,0,1
3,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,D,2.0,2.0,Fulham,...,0.0,1,1,2024,Arsenal,1,9,15,5,0
4,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Home,W,3.0,1.0,Manchester Utd,...,0.0,0,0,2024,Arsenal,1,15,16,6,1
5,2023-09-17,16:30,Premier League,Matchweek 5,Sun,Away,W,1.0,0.0,Everton,...,0.0,0,0,2024,Arsenal,0,8,16,6,1

In [34]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)
train = matches[matches["date"] < "2024-01-01"]
test = matches[matches["date"] > "2024-01-01"]
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [35]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [36]:
preds = rf.predict(test[predictors])

In [38]:
from sklearn.metrics import accuracy_score

error = accuracy_score(test["target"], preds)
error

0.6474358974358975

In [39]:
# confusion matrix
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0   1
actual
0          159  41
1           69  43

In [40]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.5119047619047619

### improving precison with rolling avg

In [72]:
grouped_matches = matches.groupby("team")

In [73]:
group = grouped_matches.get_group("Arsenal").sort_values("date")

In [74]:
# consider past 3 weeks of perfomance to evaluate next
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed="left").mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [75]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,2024-04-14,16:30,Premier League,Matchweek 33,Sun,Home,L,0.0,2.0,Aston Villa,...,6,0,1.666667,0.000000,12.666667,4.000000,14.800000,0.000000,0.333333,0.333333
46,2024-04-20,19:30,Premier League,Matchweek 34,Sat,Away,W,2.0,0.0,Wolves,...,5,1,1.666667,0.666667,16.666667,4.666667,15.800000,0.333333,0.333333,0.333333
47,2024-04-23,20:00,Premier League,Matchweek 29,Tue,Home,W,5.0,0.0,Chelsea,...,1,1,1.666667,0.666667,20.333333,6.333333,15.800000,0.333333,0.333333,0.333333
48,2024-04-28,14:00,Premier League,Matchweek 35,Sun,Away,W,3.0,2.0,Tottenham,...,6,1,2.333333,0.666667,23.000000,7.666667,17.100000,0.333333,0.000000,0.000000
49,2024-05-04,12:30,Premier League,Matchweek 36,Sat,Home,W,3.0,0.0,Bournemouth,...,5,1,3.333333,0.666667,20.000000,7.333333,16.133333,0.333333,0.000000,0.000000

In [76]:
matches_rolling = matches.groupby("team").apply(
    lambda x: rolling_averages(x, cols, new_cols)
)

In [77]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 6  2020-10-04  14:00  Premier League   Matchweek 4
                        7  2020-10-17  17:30  Premier League   Matchweek 5
                        9  2020-10-25  19:15  Premier League   Matchweek 6
                        11 2020-11-01  16:30  Premier League   Matchweek 7
                        13 2020-11-08  19:15  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 38 2024-04-13  15:00  Premier League  Matchweek 33
                        39 2024-04-20  19:30  Premier League  Matchweek 34
                        40 2024-04-24  19:45  Premier League  Matchweek 29
                        41 2024-04-27  15:00  Premier League  Matchweek 35
                        42 2024-05-04  17:30  Premier League  Matchweek 36

                            day venue result   gf   ga         opponent  ...  \
team                                                                     ...
Arsenal                 6   Sun  Home      W  2.0  1.0    Sheffield Utd  ...
                        7   Sat  Away      L  0.0  1.0  Manchester City  ...
                        9   Sun  Home      L  0.0  1.0   Leicester City  ...
                        11  Sun  Away      W  1.0  0.0   Manchester Utd  ...
                        13  Sun  Home      L  0.0  3.0      Aston Villa  ...
...                         ...   ...    ...  ...  ...              ...  ...
Wolverhampton Wanderers 38  Sat  Away      D  2.0  2.0  Nott'ham Forest  ...
                        39  Sat  Home      L  0.0  2.0          Arsenal  ...
                        40  Wed  Home      L  0.0  1.0      Bournemouth  ...
                        41  Sat  Home      W  2.0  1.0       Luton Town  ...
                        42  Sat  Away      L  1.0  5.0  Manchester City  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 6          6       1    2.000000    1.333333
                        7          5       0    1.666667    1.666667
                        9          6       0    1.000000    1.666667
                        11         6       1    0.666667    1.000000
                        13         6       0    0.333333    0.666667
...                              ...     ...         ...         ...
Wolverhampton Wanderers 38         5       0    0.666667    1.666667
                        39         5       0    1.333333    1.666667
                        40         2       0    1.000000    2.000000
                        41         5       1    0.666667    1.666667
                        42         5       0    0.666667    1.333333

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 6    8.000000    3.666667    14.633333   0.666667
                        7    5.666667    3.666667    15.366667   0.000000
                        9    7.000000    3.666667    16.566667   0.666667
                        11   9.666667    4.000000    16.566667   1.000000
                        13   9.666667    2.666667    19.333333   1.000000
...                               ...         ...          ...        ...
Wolverhampton Wanderers 38  11.333333    3.666667    17.466667   0.666667
                        39  10.666667    3.666667    17.966667   0.333333
                        40   9.666667    4.000000    20.533333   0.333333
                        41  10.333333    3.333333    18.766667   0.000000
                        42  11.000000    4.000000    19.666667   0.000000

                            pk_rolling  pkatt_rolling
team
Arsenal                 6     0.000000       0.000000
                        7     0.000000       0.000000
                        9     0.000000       0.000000
                        11    0.000000       0.000000
                        13    0.333333       0.333333
...                                ...            ...
Wolverhampton Wanderers 38    0.333333       0.333333
                        39    0.333333       0.333333
                        40    0.333333       0.333333
                        41    0.000000       0.000000
                        42    0.000000       0.000000

[2905 rows x 40 columns]

In [78]:
matches_rolling = matches_rolling.droplevel("team")

In [79]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2024-04-13,15:00,Premier League,Matchweek 33,Sat,Away,D,2.0,2.0,Nott'ham Forest,...,5,0,0.666667,1.666667,11.333333,3.666667,17.466667,0.666667,0.333333,0.333333
39,2024-04-20,19:30,Premier League,Matchweek 34,Sat,Home,L,0.0,2.0,Arsenal,...,5,0,1.333333,1.666667,10.666667,3.666667,17.966667,0.333333,0.333333,0.333333
40,2024-04-24,19:45,Premier League,Matchweek 29,Wed,Home,L,0.0,1.0,Bournemouth,...,2,0,1.000000,2.000000,9.666667,4.000000,20.533333,0.333333,0.333333,0.333333
41,2024-04-27,15:00,Premier League,Matchweek 35,Sat,Home,W,2.0,1.0,Luton Town,...,5,1,0.666667,1.666667,10.333333,3.333333,18.766667,0.000000,0.000000,0.000000
42,2024-05-04,17:30,Premier League,Matchweek 36,Sat,Away,L,1.0,5.0,Manchester City,...,5,0,0.666667,1.333333,11.000000,4.000000,19.666667,0.000000,0.000000,0.000000

In [80]:
# reset indexes
matches_rolling.index = range(matches_rolling.shape[0])

In [82]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
1,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
2,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
3,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
4,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2900,2024-04-13,15:00,Premier League,Matchweek 33,Sat,Away,D,2.0,2.0,Nott'ham Forest,...,5,0,0.666667,1.666667,11.333333,3.666667,17.466667,0.666667,0.333333,0.333333
2901,2024-04-20,19:30,Premier League,Matchweek 34,Sat,Home,L,0.0,2.0,Arsenal,...,5,0,1.333333,1.666667,10.666667,3.666667,17.966667,0.333333,0.333333,0.333333
2902,2024-04-24,19:45,Premier League,Matchweek 29,Wed,Home,L,0.0,1.0,Bournemouth,...,2,0,1.000000,2.000000,9.666667,4.000000,20.533333,0.333333,0.333333,0.333333
2903,2024-04-27,15:00,Premier League,Matchweek 35,Sat,Home,W,2.0,1.0,Luton Town,...,5,1,0.666667,1.666667,10.333333,3.333333,18.766667,0.000000,0.000000,0.000000
2904,2024-05-04,17:30,Premier League,Matchweek 36,Sat,Away,L,1.0,5.0,Manchester City,...,5,0,0.666667,1.333333,11.000000,4.000000,19.666667,0.000000,0.000000,0.000000

### retraining

In [83]:
def make_predictions(data, predictors):
    train = data[data["date"] < "2024-01-01"]
    test = data[data["date"] > "2024-01-01"]
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(
        dict(actual=test["target"], predicted=preds), index=test.index
    )
    error = precision_score(test["target"], preds)
    return combined, error

In [84]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [85]:
# precision score
error

0.6091954022988506

In [86]:
combined = combined.merge(
    matches_rolling[["date", "team", "opponent", "result"]],
    left_index=True,
    right_index=True,
)

In [88]:
combined

,actual,predicted,date,team,opponent,result
131,1,0,2024-01-20,Arsenal,Crystal Palace,W
132,1,1,2024-01-30,Arsenal,Nott'ham Forest,W
133,1,0,2024-02-04,Arsenal,Liverpool,W
134,1,1,2024-02-11,Arsenal,West Ham,W
135,1,1,2024-02-17,Arsenal,Burnley,W
...,...,...,...,...,...,...
2900,0,0,2024-04-13,Wolverhampton Wanderers,Nott'ham Forest,D
2901,0,0,2024-04-20,Wolverhampton Wanderers,Arsenal,L
2902,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L
2903,1,0,2024-04-27,Wolverhampton Wanderers,Luton Town,W
2904,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L

In [89]:
# team names different in opponent, need to normalize

class MissingDict(dict):
    __missing__ = lambda self, key: key


map_values = {
    "Brighton and Hove Albion": "Brighton",
    "Manchester United": "Manchester Utd",
    "Newcastle United": "Newcastle Utd",
    "Tottenham Hotspur": "Tottenham",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves",
}
mapping = MissingDict(**map_values)

# adding into df
combined["new_team"] = combined["team"].map(mapping)

In [90]:
combined

,actual,predicted,date,team,opponent,result,new_team
131,1,0,2024-01-20,Arsenal,Crystal Palace,W,Arsenal
132,1,1,2024-01-30,Arsenal,Nott'ham Forest,W,Arsenal
133,1,0,2024-02-04,Arsenal,Liverpool,W,Arsenal
134,1,1,2024-02-11,Arsenal,West Ham,W,Arsenal
135,1,1,2024-02-17,Arsenal,Burnley,W,Arsenal
...,...,...,...,...,...,...,...
2900,0,0,2024-04-13,Wolverhampton Wanderers,Nott'ham Forest,D,Wolves
2901,0,0,2024-04-20,Wolverhampton Wanderers,Arsenal,L,Wolves
2902,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L,Wolves
2903,1,0,2024-04-27,Wolverhampton Wanderers,Luton Town,W,Wolves
2904,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L,Wolves

In [91]:
merged = combined.merge(
    combined, left_on=["date", "new_team"], right_on=["date", "opponent"]
)
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,1,0,2024-01-20,Arsenal,Crystal Palace,W,Arsenal,0,0,Crystal Palace,Arsenal,L,Crystal Palace
1,1,1,2024-01-30,Arsenal,Nott'ham Forest,W,Arsenal,0,0,Nottingham Forest,Arsenal,L,Nottingham Forest
2,1,0,2024-02-04,Arsenal,Liverpool,W,Arsenal,0,1,Liverpool,Arsenal,L,Liverpool
3,1,1,2024-02-11,Arsenal,West Ham,W,Arsenal,0,0,West Ham United,Arsenal,L,West Ham
4,1,1,2024-02-17,Arsenal,Burnley,W,Arsenal,0,0,Burnley,Arsenal,L,Burnley
...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,0,0,2024-04-13,Wolverhampton Wanderers,Nott'ham Forest,D,Wolves,0,0,Nottingham Forest,Wolves,D,Nottingham Forest
276,0,0,2024-04-20,Wolverhampton Wanderers,Arsenal,L,Wolves,1,1,Arsenal,Wolves,W,Arsenal
277,0,0,2024-04-24,Wolverhampton Wanderers,Bournemouth,L,Wolves,1,0,Bournemouth,Wolves,W,Bournemouth
278,1,0,2024-04-27,Wolverhampton Wanderers,Luton Town,W,Wolves,0,0,Luton Town,Wolves,L,Luton Town
279,0,0,2024-05-04,Wolverhampton Wanderers,Manchester City,L,Wolves,1,1,Manchester City,Wolves,W,Manchester City

In [58]:
# X win, Y lose, what happened?
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] == 0)][
    "actual_x"
].value_counts()

actual_x
1    195
0    152
Name: count, dtype: int64

In [94]:
195 / 347

0.5619596541786743